management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
spring:
  security:
    user:
      name: ben
      password: runchey
      roles: ["ADMIN"]